---
name: 🐞 Bug Report
description: Report a problem or unexpected behavior
title: "[Bug] <brief description>"
labels: [bug]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the details below to help us understand and resolve the issue.

  - type: input
    id: environment
    attributes:
      label: 🧪 Environment
      description: What system or setup were you using?
      placeholder: e.g., Windows 11, GitHub Desktop v3.2

  - type: textarea
    id: steps
    attributes:
      label: 🔁 Steps to Reproduce
      description: Describe how to reproduce the issue
      placeholder: Step-by-step instructions

  - type: textarea
    id: expected
    attributes:
      label: ✅ Expected Behavior
      description: What did you expect to happen?

  - type: textarea
    id: actual
    attributes:
      label: ❌ Actual Behavior
      description: What actually happened?

  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots or Logs
      description: If applicable, add screenshots or error logs
